<?php require 'templates/header.phtml' ?>

<form id="form" action="agregado" method="POST" class="my-4">
    <label>TÍTULO</label>
    <input name="texto" type="text">
    <label>AUTOR/A</label>
    <input name="autor" type="text" min="1">
    <label>CATEGORÍA</label>
    <select name="categoria" class="form-select" aria-label="Default select example">
        <option selected>Seleccione categoría</option>
        <option value="1">Latinoamericano</option>
        <option value="2">Poesía</option>
        <option value="3">Cuento</option>
        <option value="4">Novela</option>
    </select>
    <input type="submit">
    <?php if ($id != null) : ?>
        <p>AGREGADO</p>
    <?php endif ?>
</form>

<?php require 'templates/footer.phtml' ?>