<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"><?= $autor->nombre ?></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Fecha de Nacimiento: <?= $autor->fecha_nacimiento ?></li>
            <li class="list-group-item">Nacionalidad: <?= $autor->nacionalidad ?></li>
            
        </ul>
    </div>
</div>