<?php require 'templates/Header.phtml' ?>

<form class="row g-3 d-flex justify-content-between align-items-end" method="POST" action="modificarTexto/<?= $texto->id_texto ?>">
  <div class="col-md-2 text-center">
    <h3 class="form-label">Nombre</h3>
    <h4 class="form-control" id="nombre"><?= $texto->nombre ?></h4>
    <input type="text" class="form-control" name="nombre">
  </div>
  <div class="col-md-1 text-center">
    <h3 class="form-label">Fecha</h3>
    <h4 class="form-control" id="fecha"><?= $texto->fecha ?></h4>
    <input type="number" class="form-control" name="Fecha">
  </div>
  <!-- ojo aca -->
  <div class="col-md-2 text-center">
    <h3 class="form-label">stock</h3>
    <h4 class="form-control h4-custom" id="stock"><?= $texto->stock ?></h4>
    <input type="number" class="form-control" name="stock">
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">valor</h3>
    <h4 class="form-control h4-custom" id="valor"><?= $texto->valor ?></h4>
    <input type="number" class="form-control" name="valor">
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">autor</h3>
    <h4 class="form-select" id="autor"><?= $texto->nombre_autor ?></h4>
    <select name="id_autor" class="form-select">
      <option selected disabled>Seleccionar...</option>
      <?php foreach ($autores as $autor) { ?>
        <option value="<?= $autor->id_autor ?>"><?= $autor->nombre ?></option>
      <?php } ?>
    </select>
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Modificar</button>
  </div>
</form>
<a href="listarTextos" class="btn btn-primary mt-3">Volver</a>

<?php require 'templates/Footer.phtml' ?>