<?php require 'templates/Header.phtml' ?>

<form class="row g-3 d-flex justify-content-between align-items-end" method="POST" action="modificarAutor/<?= $autor->id_autor ?>">
  <div class="col-md-2 text-center">
    <h3 class="form-label">Apellido y Nombre:</h3>
    <h4 class="form-control" id="nombre"><?= $autor->nombre ?></h4>
    <input type="text" class="form-control" name="nombre">
  </div>

  <div class="col-md-1 text-center">
    <h3 class="form-label">Fecha Nacimiento:</h3>
    <h4 class="form-control" id="fecha_nacimiento"><?= $autor->fecha_nacimiento ?></h4>
    <input type="date" class="form-control" name="fecha_nacimiento">
  </div>

  <div class="col-md-2 text-center">
    <h3 class="form-label">Nacionalidad:</h3>
    <h4 class="form-control" id="nacionalidad"><?= $autor->nacionalidad ?></h4>
    <input type="text" class="form-control" name="nacionalidad">
  </div>

  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Modificar</button>
  </div>
</form>
<a href="listarAutores" class="btn btn-primary mt-3">Volver</a>

<?php require 'templates/Footer.phtml' ?>