<form class="row g-3 d-flex justify-content-between align-items-end" method="POST" action="agregarTexto">
  <div class="col-md-2">
    <label for="nombre" class="form-label">Título:</label>
    <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Título">
  </div>

  <div class="col-md-2">
    <label for="stock" class="form-label">Stock:</label>
    <input type="text" class="form-control" name="stock" id="stock" placeholder="Disponibilidad">
  </div>

  <div class="col-md-2">
    <label for="fecha" class="form-label">Fecha de publicación:</label>
    <input type="date" class="form-control" name="fecha" id="fecha">
  </div>

  <div class="col-md-2">
    <label for="valor" class="form-label">Valor:</label>
    <input type="number" class="form-control" name="valor" id="valor" placeholder="$">
  </div>

  <div class="col-md-2">
    <label for="autor" class="form-label">Autor/a:</label>
    <select name="id_autor" id="autor" class="form-select">
      <option selected disabled>Seleccionar</option>
      <?php foreach ($autores as $autor) { ?>
        <option value="<?= $autor->id_autor ?>"><?= $autor->nombre ?></option>
      <?php } ?>
    </select>
  </div>

  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Agregar</button>
  </div>
</form>