<div class="header">
    <nav class="navbar">
        <div class="logo">
            <img src=<?php echo "IMG/logo.png" ?> alt="Logo Librería Virtual" width="130px" height="130px">
        </div>

        <div class="subtítulo">
            <?php
            $subtitulo = "El lugar donde encontrarás el libro que deseas";
            echo "<h1>$subtitulo</h1>";
            ?>
        </div>

        <div class="menú">
            <ul>
                <li><a href="index.phtml">INICIO</a></li>
                <li><a href="registrarse.phtml">REGISTRATE</a></li>
                <li><a href="home.phtml">LIBRERÍA</a></li>
                <li><a href="sobreNos.phtml">SOBRE NOSOTROS/AS</a></li>
            </ul>
        </div>
    </nav>
</div>