<?php require 'templates/header.phtml' ?>

<div class="text-center">
    <h1>Portal online de la librería</h1>
    <h3>Explora nuestra selección</h3>
</div>
<div class="secciones mt-5">
    <div class="row">
        <div class="col-md-6">
            <section class="textos bg-light p-3">
                <h3>Libros</h3>

                <a class="btn btn-primary" href="listarTextos">Navegar Libros</a>
            </section>
        </div>
        <div class="col-md-6">
            <section class="autores bg-light p-3">
                <h3>Autores</h3>

                <a class="btn btn-primary" href="listarAutores">Navegar Autores</a>
            </section>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>