<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LIBRERÍA VIRTUAL</title>

    <!--link css-->
    <link rel="stylesheet" href="CSS/styles.css">

</head>

<body>
    <div class="contenedor">
        <?php require 'templates/header1.phtml' ?>
        <?php require 'templates/footer1.phtml' ?>
    </div>
</body>

</html>