<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LIBRERÍA VIRTUAL</title>

    <!--link css-->
    <link rel="stylesheet" href="CSS/formStyle.css">

</head>

<body>
    <div class="contenedor">
        <?php require 'templates/header1.phtml' ?>

        <div class="informacion">
            <p><?php echo "¿Necesitás ese libro? ¿Querés saber qué libros tiene publicados tu autor/a preferido/a?" ?></p>
            <p><?php echo "Nuestro sitio web se encarga de ayudarte a encontrarlo!" ?></p>
            <p><?php echo "Solo buscalo en el explorador que tenemos disponible en la solapa 'LIBRERÍA'," ?></p>
            <p><?php echo "y te mostramos la información necesaria para que lo puedas obtener en la tienda que lo vende..." ?></p>
            <p><?php echo "HACÉ LA PRUEBA!" ?></p>
        </div>
    </div>
</body>

</html>