<?php require 'templates/header.phtml' ?>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"><?= $texto->nombre ?></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Fecha de publicación: <?= $texto->fecha ?></li>
            <li class="list-group-item">Stock: <?= $texto->stock ?></li>
            <li class="list-group-item">Valor: $ <?= $texto->valor ?></li>
            <li class="list-group-item">Autor/a: <?= $texto->nombre_autor ?></li>
        </ul>
    </div>
    <a href="listarTextos" class="btn btn-primary mt-3">Volver</a>
</div>

<?php require 'templates/footer.phtml' ?>